### ISSUE TITLE
Does Svelte Sight work in the Svelte REPL?

### ISSUE THREAD

**Issue by Danny-Engelman** [oslabs-beta/svelte-sight#51]
The F12 console for the Svelte Sight Tab shows:

![](https://i.imgur.com/nGNsacT.jpg)

**Comment by kennethtrang** [comment]
Svelte Sight does not currently work in the Svelte REPL. Instead, try creating your own Svelte app and running it on localhost in the browser in development mode, then open up Chrome DevTools (F12) and navigate to the "Svelte Sight" panel.

*Currently the Svelte Sight extension is down due to a bug, but it should be resolved within the next few days. I'll update you when it is back online. Thank you for your interest!

**Comment by Danny-Engelman** [comment]
tnx, 

Your code reads the contents of a Browser Tab (I presume). 
The REPL has the same content in an IFrame:

![](https://i.imgur.com/WL8bGDX.jpg)

I am using the REPL as my main Svelte IDE,   
Because it is great for rapid prototyping and sharing UIs with (end)users often.  
Have developed an [extension](https://chrome.google.com/webstore/detail/svelte-repl-meister/nmncamfbjoeickkimpgfghdiklhfbikh) to add some extra IDE features like autosave and search
